EXECUTE CORE.CAMPUS('MU','UNIVERSITY OF MISSOURI - COLUMBIA CAMPUS',1);
EXECUTE CORE.CAMPUS('UMSL','UNIVERSITY OF MISSOURI - ST. LOUIS CAMPUS',1);
EXECUTE CORE.CAMPUS('UMKC','UNIVERSITY OF MISSOURI - KANSAS CITY CAMPUS',1);
EXECUTE CORE.CAMPUS('MST','MISSOURI SCIENCE AND TECHNOLOGY - ROLLA CAMPUS',1);
EXECUTE CORE.CAMPUS('UMSYS', 'UNIVERSITY OF MISSOURI - SYSTEM', 1);

COMMIT;

