EXECUTE CORE.CAMPUSUSER('MU','PROJEX4');
EXECUTE CORE.CAMPUSUSER('UMSL','PROJEX4');
EXECUTE CORE.CAMPUSUSER('UMKC','PROJEX4');
EXECUTE CORE.CAMPUSUSER('MST','PROJEX4');
EXECUTE CORE.CAMPUSUSER('UMSYS','PROJEX4');

EXECUTE SECURITY.SECURITYGROUPUSER('SYSTEMUSERS','PROJEX4');
EXECUTE SECURITY.SECURITYGROUPUSER('FACILITIES','PROJEX4');

COMMIT;

