EXECUTE CORE.CAMPUSUSER('MU','REPORTCENTER');
EXECUTE CORE.CAMPUSUSER('UMSL','REPORTCENTER');
EXECUTE CORE.CAMPUSUSER('UMKC','REPORTCENTER');
EXECUTE CORE.CAMPUSUSER('MST','REPORTCENTER');
EXECUTE CORE.CAMPUSUSER('UMSYS','REPORTCENTER');

EXECUTE CORE.SECURITYGROUPUSER('ADMINISTRATORS','REPORTCENTER');

COMMIT;

