CREATE OR REPLACE PACKAGE COREPROPERTY AS

FUNCTION PROPERTY (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREFIDTYPE IN VARCHAR2, VREFID in VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) RETURN VARCHAR2;

PROCEDURE SYSTEMPROPERTY(VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE CAMPUSPROPERTY (VCAMPUS IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE OBJECTCLASSPROPERTY (VOBJECTCLASS IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE USERPROPERTY (VUSERID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE SECURITYGROUPPROPERTY (VSECURITYGROUPNAME IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
/* PROCEDURE OBJECTUSERPROPERTY (VOBJECTUSERID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2); */

END COREPROPERTY;
/

