CREATE OR REPLACE PACKAGE BODY COREPROPERTY AS

FUNCTION PROPERTY(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREFIDTYPE IN VARCHAR2, VREFID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2)
RETURN VARCHAR2 IS
NID VARCHAR2(10);
BEGIN
	IF VID IS NULL THEN
		SELECT PROPERTYSEQ.NEXTVAL INTO NID FROM DUAL;
	ELSE 
		NID := VID;
	END IF;

	MERGE INTO PROPERTIES A
	USING (SELECT ID FROM (SELECT ID FROM PROPERTIES WHERE ID = NID UNION ALL SELECT NULL ID FROM DUAL) WHERE ROWNUM = 1) B
	ON (A.ID = B.ID)
	WHEN MATCHED THEN 
	UPDATE SET A.ROWSTAMP = VROWSTAMP, A.REFIDTYPE = VREFIDTYPE, A.REFID = VREFID, A.PROPERTY = VPROPERTY, A.VALUE = VVALUE
	WHEN NOT MATCHED THEN
	INSERT (A.ID, A.ROWSTAMP, A.REFIDTYPE, A.REFID, A.PROPERTY, A.VALUE) VALUES 
		(NID, VROWSTAMP, VREFIDTYPE, VREFID, VPROPERTY, VVALUE);

	IF SQL%ROWCOUNT = 0 THEN
		NID := NULL;
	END IF;

	RETURN NID;
	
END PROPERTY;

PROCEDURE SYSTEMPROPERTY (VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS
NID VARCHAR2(10);
BEGIN
	NID := PROPERTY(null,'AAAA','SYSTEM',null,VPROPERTY, VVALUE);
END SYSTEMPROPERTY;

PROCEDURE CAMPUSPROPERTY (VCAMPUS IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS
NID VARCHAR2(10);
NREFID VARCHAR2(10);
BEGIN
	SELECT ID INTO NREFID FROM CAMPUSES WHERE CAMPUS = VCAMPUS;
	NID := PROPERTY(null,'AAAA', 'CAMPUS', NREFID, VPROPERTY, VVALUE);
END CAMPUSPROPERTY;

PROCEDURE OBJECTCLASSPROPERTY (VOBJECTCLASS IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS 
NID VARCHAR2(10);
NREFID VARCHAR2(10);
BEGIN
	SELECT ID INTO NREFID FROM OBJECTCLASSES WHERE OBJECTCLASS = VOBJECTCLASS;
	NID := PROPERTY(null,'AAAA', 'OBJECTCLASS', NREFID, VPROPERTY, VVALUE);
END OBJECTCLASSPROPERTY;


PROCEDURE USERPROPERTY (VUSERID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS 
NID VARCHAR2(10);
BEGIN
	NID := PROPERTY(null,'AAAA', 'USER', VUSERID, VPROPERTY, VVALUE);
END USERPROPERTY;

PROCEDURE SECURITYGROUPPROPERTY (VSECURITYGROUPNAME IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS 
NID VARCHAR2(10);
NREFID VARCHAR2(10);
BEGIN
	SELECT ID INTO NREFID FROM SECURITYGROUPS WHERE SECURITYGROUPNAME = VSECURITYGROUPNAME;
	NID := PROPERTY(null,'AAAA', 'SECURITYGROUP', NREFID, VPROPERTY, VVALUE);
END SECURITYGROUPPROPERTY;

/* PROCEDURE REGISTER_OBJECTUSERPROPERTY (VOBJECTUSERID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) IS 
NID VARCHAR2(10);
BEGIN
	NID := PROPERTY(null,'AAAA', 'OBJECTUSER', VOBJECTUSERID, VPROPERTY, VVALUE);
END REGISTER_OBJECTUSERPROPERTY; */

END COREPROPERTY;
/

