CREATE SEQUENCE EMAILTEMPLATESEQ;

CREATE TABLE EMAILTEMPLATES (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	EMAILNAME VARCHAR2(200),
	EMAILSUBJECT VARCHAR2(200),
	CONTENT VARCHAR2(4000),
	HELPTEXT VARCHAR2(200),
	ISACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
	CREATEDBY VARCHAR2(10) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	MODIFIEDBY VARCHAR2(10) NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT EMAIL_U UNIQUE (EMAILNAME,EMAILSUBJECT)
);

CREATE OR REPLACE TRIGGER EMAILTEMPLATES_T 
BEFORE INSERT OR UPDATE ON EMAILTEMPLATES
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
	   RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/
