CREATE SEQUENCE EMAILDETAILSEQ;

CREATE TABLE EMAILDETAILS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	USERID VARCHAR2(25) NOT NULL,
	EMAILTEMPLATEID VARCHAR2(10) NOT NULL,
	INVITATIONCODE VARCHAR2(10) NOT NULL, /* SHOULD THIS BE HERE */
	EMAILADDRESS VARCHAR2(50) NOT NULL,
	ISSEND NUMBER(1) DEFAULT 0 NOT NULL, /* IS THIS NECESSARY */
	SENDDATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT EMAILDETAILS_FK1 FOREIGN KEY (USERID) REFERENCES USERS (ID),
	CONSTRAINT EMAILDETAILS_FK2 FOREIGN KEY (EMAILTEMPLATEID) REFERENCES EMAILTEMPLATES (ID)	
);

CREATE OR REPLACE TRIGGER EMAILDETAILS_T 
BEFORE INSERT OR UPDATE ON EMAILDETAILS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
	   RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/
