CREATE OR REPLACE PACKAGE EMAIL AS

FUNCTION EMAILTEMPLATE (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VEMAILNAME IN VARCHAR2, VEMAILSUBJECT IN VARCHAR2, VCONTENT IN VARCHAR2, VHELPTEXT IN VARCHAR2,
	VISACTIVE IN NUMBER, VCREATEDBY IN VARCHAR2, VCREATED IN TIMESTAMP, VMODIFIEDBY IN VARCHAR2, VMODIFIED IN TIMESTAMP) RETURN VARCHAR2;
	
PROCEDURE EMAILTEMPLATE (VEMAILNAME IN VARCHAR2, VEMAILSUBJECT IN VARCHAR2, VCONTENT IN VARCHAR2);

FUNCTION EMAILDETAIL ( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VUSERID IN VARCHAR2, VEMAILTEMPLATEID IN VARCHAR2,
	VINVITATIONCODE IN VARCHAR2, VEMAILADDRESS IN VARCHAR2, VISSEND IN NUMBER, VSENDDATE IN TIMESTAMP ) RETURN VARCHAR2;

FUNCTION EMAILLOG (VID IN VARCHAR2, VEMAILADDRESS IN VARCHAR2, VSENDDATE IN TIMESTAMP, VSTATUSMESSAGE IN VARCHAR2) RETURN VARCHAR2;
	
END EMAIL;
/

SHO ERRORS;

