CREATE SEQUENCE APPLICATIONRIGHTSEQ;

CREATE TABLE APPLICATIONRIGHTS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	APPLICATIONID VARCHAR2(10) NOT NULL,
	RIGHT VARCHAR2(200) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT APPLICATIONRIGHTS_U UNIQUE (APPLICATIONID, RIGHT),
	CONSTRAINT APPLICATIONRIGHTS_FK1 FOREIGN KEY (APPLICATIONID) REFERENCES APPLICATIONS (ID)
);

CREATE OR REPLACE TRIGGER APPLICATIONRIGHTS_T 
BEFORE INSERT OR UPDATE ON APPLICATIONRIGHTS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

        SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE INDEX APPLICATIONRIGHT_NDX1 ON APPLICATIONRIGHTS (APPLICATIONID);
CREATE INDEX APPLICATIONRIGHT_NDX2 ON APPLICATIONRIGHTS (ID, APPLICATIONID);

CREATE MATERIALIZED VIEW LOG ON APPLICATIONRIGHTS WITH ROWID, SEQUENCE(APPLICATIONID, RIGHT), PRIMARY KEY INCLUDING NEW VALUES;
ALTER MATERIALIZED VIEW LOG FORCE ON APPLICATIONRIGHTS ADD ROWID;


