CREATE SEQUENCE SECURITYGROUPUSERTYPESEQ;

CREATE TABLE SECURITYGROUPUSERTYPES (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	SECURITYGROUPID VARCHAR2(10) NOT NULL,
	USERTYPE VARCHAR2(20) NOT NULL,
	REGISTRATIONMETHOD VARCHAR2(20) NOT NULL,
	ISDEFAULT NUMBER(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT SECURITYGROUPUSERTYPES_U UNIQUE (SECURITYGROUPID, USERTYPE),
	CONSTRAINT SECURITYGROUPUSERTYPES_FK1 FOREIGN KEY (SECURITYGROUPID) REFERENCES SECURITYGROUPS (ID)
);

CREATE OR REPLACE TRIGGER SECURITYGROUPUSERTYPES_T 
BEFORE INSERT OR UPDATE ON SECURITYGROUPUSERTYPES
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;
	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/
