CREATE OR REPLACE VIEW SECURITYGROUPUSERSVIEW AS
SELECT 
	A.ID,
	A.ROWSTAMP,
	A.SECURITYGROUPID,
	A.USERID,
	B.SECURITYGROUPNAME,
	C.USERLOGIN,
	C.USERTYPE
FROM 
	SECURITYGROUPUSERS A
INNER JOIN 
	SECURITYGROUPS B ON A.SECURITYGROUPID = B.ID
INNER JOIN USERS C ON A.USERID = C.ID ;
	
