
CREATE MATERIALIZED VIEW PERMISSIONSMVIEW 
TABLESPACE PROJEXMVIEWS
PARALLEL BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
AS
SELECT 
	B.ID,
	A.ID AS APPLICATIONPERMISSIONID,
	A.REFID, 
	A.REFIDTYPE,
	A.APPLICATIONID,
	B.PERMISSIONVALUE,
	B.APPLICATIONRIGHTID,
	C.NAME AS APPLICATIONNAME,
	D.RIGHT,
	CASE 
		WHEN A.REFIDTYPE = 'SECURITYGROUP' THEN E.SECURITYGROUPNAME
		WHEN A.REFIDTYPE = 'ROLE' THEN F.DESCRIPTION
		WHEN A.REFIDTYPE = 'USER' THEN G.USERLOGIN
	END AS DESCRIPTION 
FROM APPLICATIONPERMISSIONS A 
INNER JOIN APPLICATIONS C ON C.ID = A.APPLICATIONID
INNER JOIN PERMISSIONS B ON B.APPLICATIONPERMISSIONID = A.ID
INNER JOIN APPLICATIONRIGHTS D ON D.ID = B.APPLICATIONRIGHTID AND D.APPLICATIONID = A.APPLICATIONID
LEFT OUTER JOIN SECURITYGROUPS E ON E.ID = A.REFID AND A.REFIDTYPE = 'SECURITYGROUP'
LEFT OUTER JOIN ROLES F ON F.ID = A.REFID AND A.REFIDTYPE = 'ROLE'
LEFT OUTER JOIN USERS G ON G.ID = A.REFID AND A.REFIDTYPE = 'USER';

ALTER TABLE PERMISSIONSMVIEW NOLOGGING INMEMORY;

CREATE INDEX PERMISSIONSMVIEW_NDX1 ON PERMISSIONSMVIEW (REFID, REFIDTYPE);
CREATE INDEX PERMISSIONSMVIEW_NDX2 ON PERMISSIONSMVIEW (APPLICATIONNAME, RIGHT);


 
