CREATE OR REPLACE PACKAGE SECURITY AS

FUNCTION APPLICATIONRIGHT( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VAPPLICATIONID IN VARCHAR2, VRIGHT IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE APPLICATIONRIGHT(VAPPLICATION IN VARCHAR2, VRIGHT IN VARCHAR2);

FUNCTION OBJECTCLASSRIGHT(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VOBJECTCLASS IN VARCHAR2, VRIGHT IN VARCHAR2) RETURN VARCHAR2; 
PROCEDURE OBJECTCLASSRIGHT (VOBJECTCLASS IN VARCHAR2, VRIGHT IN VARCHAR2);

FUNCTION SECURITYGROUP (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VSECURITYGROUPNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER, VISSYSTEMSECURITYGROUP IN NUMBER) RETURN VARCHAR2;
PROCEDURE SECURITYGROUP(VSECURITYGROUPNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER, VISSYSTEMSECURITYGROUP IN NUMBER);

FUNCTION SECURITYGROUPUSERTYPE(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VSECURITYGROUPID IN VARCHAR2, VUSERTYPE IN VARCHAR2, VREGISTRATIONMETHOD IN VARCHAR2, VISDEFAULT IN NUMBER) RETURN VARCHAR2;
PROCEDURE SECURITYGROUPUSERTYPE(VSECURITYGROUPNAME IN VARCHAR2, VUSERTYPE IN VARCHAR2, VREGISTRATIONMETHOD IN VARCHAR2, VISDEFAULT IN NUMBER);

FUNCTION SECURITYGROUPUSER(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VSECURITYGROUPID IN VARCHAR2, VUSERID IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE SECURITYGROUPUSER(VSECURITYGROUPNAME IN VARCHAR2, VUSERLOGIN IN VARCHAR2);

FUNCTION APPLICATIONPERMISSION(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VAPPLICATIONID IN VARCHAR2, VREFID IN VARCHAR2, VREFIDTYPE IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE USERAPPLICATIONPERMISSION(VAPPLICATION IN VARCHAR2, VUSERLOGIN IN VARCHAR2);
PROCEDURE GROUPAPPLICATIONPERMISSION(VAPPLICATION IN VARCHAR2, VSECURITYGROUPNAME IN VARCHAR2);
PROCEDURE ROLEAPPLICATIONPERMISSION(VAPPLICATION IN VARCHAR2, VOBJECTCLASS IN VARCHAR2, VUSERTYPE IN VARCHAR2, VCLASSIFICATION IN VARCHAR2);

FUNCTION PERMISSION(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VAPPLICATIONPERMISSIONID IN VARCHAR2, VAPPLICATIONRIGHTID IN VARCHAR2, VPERMISSIONVALUE in VARCHAR2) RETURN VARCHAR2 ;
PROCEDURE USERPERMISSION(VAPPLICATION IN VARCHAR2, VUSERLOGIN IN VARCHAR2, VRIGHT IN VARCHAR2, VPERMISSIONVALUE IN VARCHAR2);
PROCEDURE GROUPPERMISSION(VAPPLICATION IN VARCHAR2, VSECURITYGROUPNAME IN VARCHAR2, VRIGHT IN VARCHAR2, VPERMISSIONVALUE IN VARCHAR2);
PROCEDURE ROLEPERMISSION(VAPPLICATION IN VARCHAR2, VOBJECTCLASS IN VARCHAR2, VUSERTYPE IN VARCHAR2, VCLASSIFICATION IN VARCHAR2, VRIGHT IN VARCHAR2, VPERMISSIONVALUE IN VARCHAR2);

PROCEDURE RESETAPPLICATIONSECURITY(VAPPLICATIONNAME IN VARCHAR2);

FUNCTION GETPERMISSIONVALUE(VUSERID IN VARCHAR2, VAPPLICATION IN VARCHAR2, VRIGHT IN VARCHAR2) RETURN NUMBER;
FUNCTION CANDO(VUSERID IN VARCHAR2, VAPPLICATION IN VARCHAR2, VRIGHT IN VARCHAR2) RETURN NUMBER;

END SECURITY;
/

sho err
