create user "REPORTCENTER" identified by rptUser392
profile "DEFAULT" account unlock 
default tablespace  "REPORTCENTER" temporary tablespace "TEMP";
        
grant CREATE TABLE to "REPORTCENTER";
grant ALTER ANY TABLE to "REPORTCENTER";
grant SELECT ANY TABLE to "REPORTCENTER";
grant CREATE EXTERNAL JOB to "REPORTCENTER";
grant MANAGE SCHEDULER to "REPORTCENTER";
grant SELECT ANY SEQUENCE to "REPORTCENTER";
grant READ ANY TABLE to "REPORTCENTER";
grant CREATE SYNONYM to "REPORTCENTER";
grant CREATE DATABASE LINK to "REPORTCENTER";
grant UPDATE ANY TABLE to "REPORTCENTER";
grant ALTER SESSION to "REPORTCENTER";
grant EXECUTE ANY PROCEDURE to "REPORTCENTER";
grant CREATE SESSION to "REPORTCENTER";
grant CREATE MATERIALIZED VIEW to "REPORTCENTER";
grant CREATE PUBLIC SYNONYM to "REPORTCENTER";
grant "CONNECT" to "REPORTCENTER";
grant ALTER PUBLIC DATABASE LINK to "REPORTCENTER";
grant ALTER DATABASE LINK to "REPORTCENTER";
grant CREATE PROCEDURE to "REPORTCENTER";
grant INSERT ANY TABLE to "REPORTCENTER";
grant UNLIMITED TABLESPACE to "REPORTCENTER";
grant "DBA" to "REPORTCENTER";
grant CREATE PUBLIC DATABASE LINK to "REPORTCENTER";
grant ON COMMIT REFRESH to "REPORTCENTER";
grant CREATE VIEW to "REPORTCENTER";
grant DROP PUBLIC DATABASE LINK to "REPORTCENTER";
grant DROP PUBLIC SYNONYM to "REPORTCENTER";
grant CREATE TRIGGER to "REPORTCENTER";
grant CREATE SEQUENCE to "REPORTCENTER";
