/* 

create user "PROJEX4" identified by prj4_user
profile "DEFAULT" account unlock 
default tablespace  "PROJEX" temporary tablespace "TEMP";
        
grant CREATE TABLE to "PROJEX4";
grant ALTER ANY TABLE to "PROJEX4";
grant SELECT ANY TABLE to "PROJEX4";
grant CREATE EXTERNAL JOB to "PROJEX4";
grant MANAGE SCHEDULER to "PROJEX4";
grant SELECT ANY SEQUENCE to "PROJEX4";
grant READ ANY TABLE to "PROJEX4";
grant CREATE SYNONYM to "PROJEX4";
grant CREATE DATABASE LINK to "PROJEX4";
grant UPDATE ANY TABLE to "PROJEX4";
grant ALTER SESSION to "PROJEX4";
grant EXECUTE ANY PROCEDURE to "PROJEX4";
grant CREATE SESSION to "PROJEX4";
grant CREATE MATERIALIZED VIEW to "PROJEX4";
grant CREATE PUBLIC SYNONYM to "PROJEX4";
grant "CONNECT" to "PROJEX4";
grant ALTER PUBLIC DATABASE LINK to "PROJEX4";
grant ALTER DATABASE LINK to "PROJEX4";
grant CREATE PROCEDURE to "PROJEX4";
grant INSERT ANY TABLE to "PROJEX4";
grant UNLIMITED TABLESPACE to "PROJEX4";
grant "DBA" to "PROJEX4";
grant CREATE PUBLIC DATABASE LINK to "PROJEX4";
grant ON COMMIT REFRESH to "PROJEX4";
grant CREATE VIEW to "PROJEX4";
grant DROP PUBLIC DATABASE LINK to "PROJEX4";
grant DROP PUBLIC SYNONYM to "PROJEX4";
grant CREATE TRIGGER to "PROJEX4";
grant CREATE SEQUENCE to "PROJEX4";

*/
