CREATE SEQUENCE REPORTRUNHISTORYSEQ;

CREATE TABLE REPORTRUNHISTORY (
	ID VARCHAR2(10) NOT NULL,
	USERID VARCHAR2(10) NOT NULL,
	REPORTID VARCHAR2(10) NOT NULL,
	FILEFORMAT VARCHAR2(20) NOT NULL,
	RANON TIMESTAMP NOT NULL,
	FILELOCATION VARCHAR2(2000) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT REPORTRUNHISTORY_FK1 FOREIGN KEY (USERID) REFERENCES USERS (ID),
	CONSTRAINT REPORTRUNHISTORY_FK2 FOREIGN KEY (REPORTID) REFERENCES REPORTS (ID)
);

CREATE OR REPLACE TRIGGER REPORTRUNHISTORY_T 
BEFORE UPDATE ON REPORTRUNHISTORY
FOR EACH ROW
BEGIN
        RAISE_APPLICATION_ERROR(-20001,'Updates Not Allowed.');
END;
/

CREATE INDEX REPORTRUNHISTORY_IDX10 ON REPORTRUNHISTORY (REPORTID);
CREATE INDEX REPORTRUNHISTORY_IDX11 ON REPORTRUNHISTORY (USERID, REPORTID);
CREATE INDEX REPORTRUNHISTORY_IDX12 ON REPORTRUNHISTORY (RANON);

