CREATE SEQUENCE REPORTRUNPARAMETERSSEQ;

CREATE TABLE REPORTRUNPARAMETERS (
ID VARCHAR2(10) NOT NULL,
REPORTRUNHISTORYID VARCHAR2(10) NOT NULL,
PARAMETERNUMBER NUMBER(5) DEFAULT 1 NOT NULL,
PARAMETERNAME VARCHAR2(100) NOT NULL,
PARAMETERVALUE VARCHAR2(1000) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT REPORTRUNPARAMETERS_U UNIQUE (REPORTRUNHISTORYID, PARAMETERNAME),
CONSTRAINt REPORTRUNPARAMETERS_FK1 FOREIGN KEY (REPORTRUNHISTORYID) REFERENCES REPORTRUNHISTORY (ID)
);

CREATE OR REPLACE TRIGGER REPORTRUNPARAMETERS_T
BEFORE UPDATE ON REPORTRUNPARAMETERS
FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20001, 'Update report run parameter not allowed.');
END;
/

CREATE INDEX REPORTRUNPARAMETERS_IDX10 ON REPORTRUNPARAMETERS (REPORTRUNHISTORYID);
