CREATE SEQUENCE REPORTMODIFICATIONHISTORYSEQ;

CREATE TABLE REPORTMODIFICATIONHISTORY (
	ID VARCHAR2(10) NOT NULL,
	REPORTID VARCHAR2(10) NOT NULL,
	FILENAME VARCHAR2(300) NOT NULL,
	REQUESTED TIMESTAMP NOT NULL,
	REQUESTEDBY VARCHAR2(10) NOT NULL, /* SHOULD THIS BE PERSONID IN PROJEX4 */
	REQUESTERBUSINESSUNIT VARCHAR2(10),
	REQUESTERBUSINESSUNITNAME VARCHAR2(30),
	REQUESTERSUPERDIVISION VARCHAR2(10),
	REQUESTERSUPERDIVISIONNAME VARCHAR2(30),
	REQUESTERDIVISION VARCHAR2(10),
	REQUESTERDIVISIONNAME VARCHAR2(100),
	REQUESTERDEPARTMENT VARCHAR2(10),
	REQUESTERDEPARTMENTNAME VARCHAR2(100),
	REQUESTERSUBDEPARTMENT VARCHAR2(10),
	REQUESTERSUBDEPARTMENTNAME VARCHAR2(100),
	REQUESTERDEPTID VARCHAR2(10),
	REQUESTERDEPTIDNAME VARCHAR2(30),
	REASON	VARCHAR2(4000) NOT NULL,
	REGISTERED TIMESTAMP NOT NULL, 
	REGISTEREDBY VARCHAR2(10) NOT NULL, /* THIS SHOULD BE USERID IN PROJEX 4 */
	REGISTERERBUSINESSUNIT VARCHAR2(10),
	REGISTERERBUSINESSUNITNAME VARCHAR2(30),
	REGISTERERSUPERDIVISION VARCHAR2(10),
	REGISTERERSUPERDIVISIONNAME VARCHAR2(30),
	REGISTERERDIVISION VARCHAR2(10),
	REGISTERERDIVISIONNAME VARCHAR2(100),
	REGISTERERDEPARTMENT VARCHAR2(10),
	REGISTERERDEPARTMENTNAME VARCHAR2(100),
	REGISTERERSUBDEPARTMENT VARCHAR2(10),
	REGISTERERSUBDEPARTMENTNAME VARCHAR2(100),
	REGISTERERDEPTID VARCHAR2(10),
	REGISTERERDEPTIDNAME VARCHAR2(30),
	CATEGORY VARCHAR2(500),
	TOOL VARCHAR2(50),
	TOOLVERSION VARCHAR2(50),
	PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER REPORTMODIFICATIONHISTORY_T 
BEFORE UPDATE ON REPORTMODIFICATIONHISTORY
FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20001,'Updates Not Allowed.');
END;
/

CREATE INDEX REPORTMODHISTORY_IDX10 ON REPORTMODIFICATIONHISTORY (REPORTID);
