CREATE OR REPLACE VIEW REPORTSVIEW AS 
SELECT 
	A.ID, 
	A.REPORTNAME, 
	A.DESCRIPTION, 
	A.HELPTEXT, 
	A.SCREENNAME,
	A.CAMPUSID,
	A.ISALLCAMPUS,
	A.ISACTIVE,
	B.PARAMETERNUMBER,
	B.PARAMETER,
	B.PARAMETERTYPE,
	B.LISTNAME
FROM REPORTS A 
INNER JOIN REPORTPARAMETERS B ON A.ID = B.REPORTID;
