/* Handles Report modification history */

CREATE OR REPLACE TRIGGER REPORTS_T2
AFTER UPDATE ON REPORTS
FOR EACH ROW
BEGIN
	
	INSERT INTO REPORTMODIFICATIONHISTORY
	(ID, REPORTID, FILENAME, REQUESTED, REQUESTEDBY, REASON, REGISTERED, REGISTEREDBY, CATEGORY)
	VALUES 
	(REPORTMODIFICATIONHISTORYSEQ.NEXTVAL, :NEW.ID, :NEW.FILENAME, :NEW.REQUESTED, 
		:NEW.REQUESTEDBY, :NEW.REASON, :NEW.REGISTERED, :NEW.REGISTEREDBY, :NEW.CATEGORY);
	
	
END;
/

SHO ERRORS
