CREATE SEQUENCE REPORTDATASOURCESEQ;

CREATE TABLE REPORTDATASOURCES (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	REPORTID VARCHAR2(10) NOT NULL,
	DRIVERMETHOD VARCHAR2(50),
	SERVER VARCHAR2(50),
	SERVERPORT VARCHAR2(10),
	DATABASE VARCHAR2(50),
	USERNAME VARCHAR2(50),
	PASSWORD VARCHAR2(50),
	PRIMARY KEY(ID)
);

CREATE OR REPLACE TRIGGER REPORTDATASOURCES_T 
BEFORE INSERT OR UPDATE ON REPORTDATASOURCES
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
	   RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/
	
