CREATE SEQUENCE REPORTCRONTASKEMAILSEQ;

CREATE TABLE REPORTCRONTASKEMAILS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	REPORTCRONTASKID VARCHAR2(10) NOT NULL,
	EMAILADDRESS VARCHAR2(100) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT REPORTCRONTASKEMAILS_U UNIQUE (REPORTCRONTASKID, EMAILADDRESS),
	CONSTRAINT REPORTCRONTASKEMAILS_FK1 FOREIGN KEY (REPORTCRONTASKID) REFERENCES REPORTCRONTASKS (ID)
);

CREATE OR REPLACE TRIGGER REPORTCRONTASKEMAILS_T 
BEFORE INSERT OR UPDATE ON REPORTCRONTASKEMAILS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
	   RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another u
ser');
END;
/


