CREATE OR REPLACE VIEW REPORTCRONTASKDETAILS AS
SELECT 
	A.ID,
	A.ROWSTAMP,
	A.REPORTID,
	C.REPORTNAME,
	C.DESCRIPTION,
	C.SCREENNAME,
	C.CATEGORY,
	CASE 
		WHEN C.ISACTIVE = 0 THEN 0 
		WHEN A.ISACTIVE = 0 THEN 0 
		ELSE 1
	END AS ISACTIVE,
	A.SCHEDULED,
	A.SCHEDULEDBY,
	B.USERLOGIN AS SCHEDULEDBYUSERNAME,
	A.CRONEXPRESSION,
	A.FILEFORMAT,
	A.ISONETIME
FROM REPORTCRONTASKS A
INNER JOIN USERS B ON B.ID = A.SCHEDULEDBY
INNER JOIN REPORTS C ON C.ID = A.REPORTID;

