CREATE OR REPLACE VIEW REPORTLISTING AS
SELECT
	A.ID,
	A.ROWSTAMP,
	A.REPORTNAME,
	A.DESCRIPTION,
	A.HELPTEXT,
	A.ISACTIVE,
	A.FILENAME,
	A.REQUESTED,
	A.REQUESTEDBY,
	A.REQUESTERBUSINESSUNIT,
	A.REQUESTERBUSINESSUNITNAME,
	A.REQUESTERSUPERDIVISION,
	A.REQUESTERSUPERDIVISIONNAME,
	A.REQUESTERDIVISION,
	A.REQUESTERDIVISIONNAME,
	A.REQUESTERDEPARTMENT,
	A.REQUESTERDEPARTMENTNAME,
	A.REQUESTERSUBDEPARTMENT,
	A.REQUESTERSUBDEPARTMENTNAME,
	A.REQUESTERDEPTID,
	A.REQUESTERDEPTIDNAME,
	A.REASON,
	A.REGISTERED,
	A.REGISTEREDBY,
	A.CATEGORY,
	A.TOOL,
	A.TOOLVERSION,
	A.RUNTIMEENVIRONMENT,
	A.PROGRAMVERSION,
	A.STATUS,
	A.STATUSED,
	A.STATUSEDBY,
	A.ISSLOWRUNNING,
	C.SECURITYGROUPNAME,
	C.DESCRIPTION AS SECURITYGROUPDESCRIPTION,
	B.USERLOGIN,
	B.FULLNAME,
	D.CAMPUS,
	D.DESCRIPTION AS CAMPUSDESCRIPTION
FROM REPORTS A
INNER JOIN SECURITYGROUPREPORTS SGR ON SGR.REPORTID = A.ID
INNER JOIN SECURITYGROUPS C ON C.ID = SGR.SECURITYGROUPID AND C.ISACTIVE = 1
INNER JOIN SECURITYGROUPUSERS SGU ON SGU.SECURITYGROUPID = C.ID
INNER JOIN USERS B ON B.ID = SGU.USERID AND B.ISACTIVE = 1
INNER JOIN CAMPUSUSERS CU ON CU.USERID = B.ID
INNER JOIN CAMPUSREPORTS CR ON CR.REPORTID = A.ID
INNER JOIN CAMPUSES D ON D.ID = CU.CAMPUSID AND D.ID = CR.CAMPUSID AND D.ISACTIVE = 1
WHERE A.ISACTIVE = 1;



