CREATE OR REPLACE PACKAGE REPORT AS

FUNCTION REPORT (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, 
	VREPORTNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2,
	VHELPTEXT IN VARCHAR2, VISACTIVE IN NUMBER, 
	VFILENAME IN VARCHAR2, VREQUESTED IN TIMESTAMP, 
	VREQUESTEDBY IN VARCHAR2, 
	VREQUESTERBUSINESSUNIT IN VARCHAR2,
	VREQUESTERBUSINESSUNITNAME IN VARCHAR2,
	VREQUESTERSUPERDIVISION IN VARCHAR2,
	VREQUESTERSUPERDIVISIONNAME IN VARCHAR2,
	VREQUESTERDIVISION IN VARCHAR2,
	VREQUESTERDIVISIONNAME IN VARCHAR2,
	VREQUESTERDEPARTMENT IN VARCHAR2,
	VREQUESTERDEPARTMENTNAME IN VARCHAR2,
	VREQUESTERSUBDEPARTMENT IN VARCHAR2,
	VREQUESTERSUBDEPARTMENTNAME IN VARCHAR2,
	VREQUESTERDEPTID IN VARCHAR2,
	VREQUESTERDEPTIDNAME IN VARCHAR2,
	VREASON IN VARCHAR2, 
	VREGISTERED IN TIMESTAMP, VREGISTEREDBY IN VARCHAR2, 
	VCATEGORY IN VARCHAR2, VTOOL IN VARCHAR2,
	VTOOLVERSION IN VARCHAR2, VRUNTIMEENVIRONMENT IN VARCHAR2,
	VPROGRAMVERSION IN VARCHAR2, VSTATUS IN VARCHAR2, 
	VSTATUSED IN TIMESTAMP, VSTATUSEDBY IN VARCHAR2,
	VISSLOWRUNNING IN NUMBER) RETURN VARCHAR2;
	
FUNCTION REPORTRUNHISTORY (VUSERID IN VARCHAR2, VREPORTID IN VARCHAR2, VFILEFORMAT IN VARCHAR2, VFILELOCATION IN VARCHAR2 ) RETURN VARCHAR2;

FUNCTION REPORTRUNPARAMETER (VID IN VARCHAR2, VREPORTRUNHISTORYID IN VARCHAR2, VPARAMETERNUMBER IN NUMBER, 
	VPARAMETERNAME IN VARCHAR2, VPARAMETERVALUE IN VARCHAR2 ) RETURN VARCHAR2;

FUNCTION REPORTPARAMETER (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREPORTID IN VARCHAR2, 
	VPARAMETERNUMBER IN NUMBER, VPARAMETER IN VARCHAR2, VPARAMETERTYPE IN VARCHAR2, VLISTNAME IN VARCHAR2) RETURN VARCHAR2;
	
FUNCTION SECURITYGROUPREPORT(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VSECURITYGROUPID IN VARCHAR2, VREPORTID IN VARCHAR2) RETURN VARCHAR2;

FUNCTION CAMPUSREPORT(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VCAMPUSID IN VARCHAR2, VREPORTID IN VARCHAR2) RETURN VARCHAR2;

FUNCTION REPORTCRONTASK(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREPORTID IN VARCHAR2, VSCHEDULEDBY IN VARCHAR2, VSCHEDULED IN TIMESTAMP,
	VCRONEXPRESSION IN VARCHAR2, VISACTIVE IN NUMBER, VFILEFORMAT IN VARCHAR2, VISONETIME IN NUMBER) RETURN VARCHAR2;
	
FUNCTION REPORTCRONTASKPARAMETER(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREPORTCRONTASKID IN VARCHAR2, 
	VPARAMETERNUMBER IN NUMBER, VPARAMETERTYPE IN VARCHAR2, VPARAMETERNAME IN VARCHAR2, VPARAMETERVALUE IN VARCHAR2) RETURN VARCHAR2;
	
FUNCTION REPORTCRONTASKEMAIL(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREPORTCRONTASKID IN VARCHAR2, 
	VEMAILADDRESS IN VARCHAR2) RETURN VARCHAR2;

END REPORT;
/

show errors
