/* 
	USERS TABLE 
*/
CREATE SEQUENCE USERSEQ;

CREATE TABLE USERS (
	ID VARCHAR2(10) NOT NULL, 
	ROWSTAMP VARCHAR2(10) NOT NULL,
	USERLOGIN VARCHAR2(100),
	FULLNAME VARCHAR2(200),
	SORTNAME VARCHAR2(200),
	EMPLID VARCHAR(20),
	PASSWORD VARCHAR2(64),
	ISACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
	SECRETKEY VARCHAR2(10),
	CREATED DATE,
	CREATEDBY VARCHAR2(10),
	PRIMARY KEY (ID),
	CONSTRAINT USERS_U1 UNIQUE (USERLOGIN)
);

CREATE INDEX USERS_IDX1 ON USERS (USERLOGIN, ISACTIVE);

CREATE OR REPLACE TRIGGER USERS_T 
BEFORE INSERT OR UPDATE ON USERS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
	INVALIDDATA EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	IF INSERTING THEN 
		SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.SECRETKEY FROM DUAL;
	END IF;
	
	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
	   WHEN INVALIDDATA THEN
	    RAISE_APPLICATION_ERROR(-20099,'Invalid Data');
END;
/

