/* 
	CAMPUSES 

	DEFINES PARTICULAR CAMPUS VALUES. 
	MOSTLY DEFINED TO ALLOW FOREIGN KEY CONSTRAINTS TO LATER TABLES TO BE ADDED.
	MAY ADD FIELDS AS NECESSARY.
	
	Should we rename this campuses so as not to conflict with ARCHIBUS data?
	
	If we sell projex rename to Organizations.
*/

CREATE SEQUENCE CAMPUSSEQ;

CREATE TABLE CAMPUSES (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	CAMPUS VARCHAR2(20) NOT NULL, 
	DESCRIPTION VARCHAR2(100) NOT NULL,
	ISACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT CAMPUSES_U UNIQUE (CAMPUS)
);

CREATE OR REPLACE TRIGGER CAMPUSES_T 
BEFORE INSERT OR UPDATE ON CAMPUSES
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE MATERIALIZED VIEW LOG ON CAMPUSES PARALLEL WITH ROWID, SEQUENCE(CAMPUS, ISACTIVE), PRIMARY KEY INCLUDING NEW VALUES;

