/* Lists for general use */

CREATE SEQUENCE LISTSEQ;

CREATE TABLE LISTS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	LISTNAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(500) NOT NULL,
	HELPTEXT VARCHAR2(500),
	ISACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
	ISSYSTEM NUMBER(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT SETS_U UNIQUE (LISTNAME)
);

COMMENT ON TABLE LISTS IS 'GENERALLY USABLE VALUE LISTS'
/

COMMENT ON COLUMN LISTS.LISTNAME IS 'NAME OF VALUE LIST - IF SUBLIST, NAME SHOULD BE PARENTNAME.SUBLISTNAME'
/

COMMENT ON COLUMN LISTS.ISACTIVE IS 'THIS LIST IS USABLE - IF SET TO 0 VALUE LISTS WILL NOT POPULATE'
/

COMMENT ON COLUMN LISTS.ISSYSTEM IS 'THIS LIST IS REQUIRED BY THE SYSTEM TO OPERATE'
/

COMMENT ON COLUMN LISTS.DESCRIPTION IS 'BRIEFLY DESCRIBES WHAT LIST IS USED FOR'
/

CREATE OR REPLACE TRIGGER LISTS_T 
BEFORE INSERT OR UPDATE ON LISTS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE INDEX LISTS_IDX1 ON LISTS (LISTNAME, ISACTIVE);
