CREATE SEQUENCE USERLOGINHISTORYSEQ;
CREATE TABLE USERLOGINHISTORY (
	ID VARCHAR2(10),
	USERID VARCHAR2(10),
	LOGGEDIN TIMESTAMP,
	IPADDRESS VARCHAR2(30),
	PRIMARY KEY (ID),
	CONSTRAINT USERLOGINHISTORY_FK1 FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

CREATE INDEX USERLOGINHISTORY_IDX1 ON USERLOGINHISTORY (USERID);
CREATE INDEX USERLOGINHISTORY_IDX2 ON USERLOGINHISTORY (LOGGEDIN);
CREATE INDEX USERLOGINHISTORY_IDX3 ON USERLOGINHISTORY (USERID, LOGGEDIN);


