CREATE SEQUENCE CAMPUSUSERSEQ;

CREATE TABLE CAMPUSUSERS(
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	CAMPUSID VARCHAR2(10) NOT NULL,
	USERID VARCHAR2(10) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT CAMPUSUSER_U UNIQUE (CAMPUSID, USERID),
	CONSTRAINT CAMPUSUSER_FK1 FOREIGN KEY (CAMPUSID) REFERENCES CAMPUSES (ID),
	CONSTRAINT CAMPUSUSER_FK2 FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

CREATE OR REPLACE TRIGGER CAMPUSUSERS_T
BEFORE INSERT OR UPDATE ON CAMPUSUSERS
FOR EACH ROW
DECLARE
     OBJECTMODIFICATION EXCEPTION;
BEGIN
     IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
	     RAISE OBJECTMODIFICATION;
     END IF;

     SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;

     EXCEPTION
	WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE INDEX CAMPUSUSERS_IDX1 ON CAMPUSUSERS (USERID) NOLOGGING;
CREATE INDEX CAMPUSUSERS_IDX2 ON CAMPUSUSERS (CAMPUSID) NOLOGGING;
