CREATE SEQUENCE CRONTASKSEQ;
CREATE TABLE CRONTASKS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	JAVACLASS VARCHAR2(2000) NOT NULL,
	DESCRIPTION VARCHAR2(500) NOT NULL,
	CRONEXPRESSION VARCHAR2(200) NOT NULL,
	ISACTIVE NUMBER(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT CRONTASKS_U UNIQUE (JAVACLASS, CRONEXPRESSION)
);

CREATE OR REPLACE TRIGGER CRONTASKS_T 
BEFORE INSERT OR UPDATE ON CRONTASKS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE INDEX CRONTASKS_IDX1 ON CRONTASKS (ISACTIVE);
