CREATE SEQUENCE CRONTASKRUNSEQ;

CREATE TABLE CRONTASKRUNS (
	ID VARCHAR2(10) NOT NULL,
	JAVACLASS VARCHAR2(2000) NOT NULL,
	SERVER VARCHAR2(1000) NOT NULL,
	RUNSTART TIMESTAMP NOT NULL,
	RUNEND TIMESTAMP NOT NULL,
	STATUS VARCHAR2(100) NOT NULL,
	ERROR VARCHAR2(500),
	PRIMARY KEY (ID)
);

CREATE INDEX CRONTASKRUNS_IDX1 ON CRONTASKRUNS (JAVACLASS);
CREATE INDEX CRONTASKRUNS_IDX2 ON CRONTASKRUNS (RUNSTART);
CREATE INDEX CRONTASKRUNS_IDX3 ON CRONTASKRUNS (STATUS);
