CREATE OR REPLACE VIEW CAMPUSUSERLISTING
AS
SELECT 
A.ID,
A.ROWSTAMP,
A.CAMPUSID,
A.USERID,
B.USERLOGIN,
B.FULLNAME,
B.SORTNAME,
B.EMPLID,
C.CAMPUS,
C.DESCRIPTION AS CAMPUSDESCRIPTION
FROM CAMPUSUSERS A
INNER JOIN USERS B ON B.ID = A.USERID AND B.ISACTIVE = 1
INNER JOIN CAMPUSES C ON C.ID = A.CAMPUSID AND C.ISACTIVE = 1;
