CREATE OR REPLACE VIEW CAMPUSUSERSVIEW AS
SELECT 
	A.ID,
	A.ROWSTAMP,
	A.CAMPUS,
	B.CAMPUSID,
	B.USERID,
	C.USERLOGIN,
	C.USERTYPE
FROM CAMPUSES A 
INNER JOIN CAMPUSUSERS B ON
	B.CAMPUSID = A.ID 
INNER JOIN USERS C ON
	C.ID = B.USERID;
