CREATE SEQUENCE BULLETINSEQ INCREMENT BY 1 NOCACHE;

CREATE TABLE BULLETINS (
	ID VARCHAR2(10) NOT NULL,
	ROWSTAMP VARCHAR2(10) NOT NULL,
	LANGUAGE VARCHAR2(10) DEFAULT 'EN' NOT NULL,
	PERIODSTART TIMESTAMP,
	PERIODEND TIMESTAMP,
	BULLETINTEXT VARCHAR2(1000),
	CREATED TIMESTAMP,
	CREATEDBY VARCHAR2(10),
	PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER BULLETINS_T 
BEFORE INSERT OR UPDATE ON BULLETINS
FOR EACH ROW
DECLARE 
	OBJECTMODIFICATION EXCEPTION;
BEGIN
	IF UPDATING AND NOT :NEW.ROWSTAMP = :OLD.ROWSTAMP THEN
		RAISE OBJECTMODIFICATION;
	END IF;

	SELECT DBMS_RANDOM.STRING('U',10) INTO :NEW.ROWSTAMP FROM DUAL;
	EXCEPTION 
	   WHEN OBJECTMODIFICATION THEN
		RAISE_APPLICATION_ERROR(-20100,'Record has been modified by another user');
END;
/

CREATE INDEX BULLETINS_IDX1 ON BULLETINS (PERIODSTART);
CREATE INDEX BULLETINS_IDX2 ON BULLETINS (PERIODEND);

