CREATE OR REPLACE VIEW SECURITYGROUPUSERLISTING AS
SELECT
A.ID,
A.ROWSTAMP,
A.SECURITYGROUPID,
A.USERID,
A.CREATED,
B.SECURITYGROUPNAME,
B.DESCRIPTION,
C.USERLOGIN,
C.FULLNAME,
C.SORTNAME,
C.EMPLID
FROM SECURITYGROUPUSERS A
INNER JOIN SECURITYGROUPS B ON B.ID = A.SECURITYGROUPID AND B.ISACTIVE = 1
INNER JOIN USERS C ON C.ID = A.USERID AND C.ISACTIVE = 1;
