CREATE OR REPLACE PACKAGE CORE AS

FUNCTION CAMPUS(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VCAMPUS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER) RETURN VARCHAR2;
PROCEDURE CAMPUS (VCAMPUS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER); 

FUNCTION LIST (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLISTNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VHELPTEXT IN VARCHAR2, VISACTIVE IN NUMBER, VISSYSTEM IN NUMBER) RETURN VARCHAR2;
PROCEDURE LIST (VLISTNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VHELPTEXT IN VARCHAR2, VISACTIVE IN NUMBER, VISSYSTEM IN NUMBER);

FUNCTION LISTITEM (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLISTID IN VARCHAR2, VISALLCAMPUS IN NUMBER, VDISPLAYORDER IN NUMBER, VSYSTEMVALUE IN VARCHAR2, VVALUE IN VARCHAR2, VISDEFAULT IN NUMBER, VDESCRIPTION IN VARCHAR2) RETURN VARCHAR2; 
FUNCTION CAMPUSLISTITEM (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VCAMPUSID IN VARCHAR2, VLISTITEMID IN VARCHAR2, VISDEFAULT IN NUMBER) RETURN VARCHAR2;
PROCEDURE LISTITEM (VLISTNAME IN VARCHAR2, VCAMPUS IN VARCHAR2, VISALLCAMPUS IN NUMBER, VDISPLAYORDER IN NUMBER, VSYSTEMVALUE IN VARCHAR2, VVALUE IN VARCHAR2, VISDEFAULT IN NUMBER, VDESCRIPTION IN VARCHAR2); 

FUNCTION APPLICATION (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER) RETURN VARCHAR2;
PROCEDURE APPLICATION (VNAME IN VARCHAR2, VDESCRIPTION in VARCHAR2);

FUNCTION AUTHPROVIDER (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VNAME IN VARCHAR2, VURL IN VARCHAR2, VICON IN VARCHAR2, VDISPLAYORDER IN NUMBER, VAUTHMETHOD IN VARCHAR2, VISACTIVE IN NUMBER, VREQUIRESNAME IN NUMBER, VREQUIRESPASSWORD IN NUMBER, VAUTHKEY IN VARCHAR2, VAUTHSECRET IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE AUTHPROVIDER (VNAME IN VARCHAR2, VURL IN VARCHAR2, VICON IN VARCHAR2, VDISPLAYORDER IN NUMBER, VAUTHMETHOD IN VARCHAR2, VISACTIVE IN NUMBER, VREQUIRESNAME IN NUMBER, VREQUIRESPASSWORD IN NUMBER, VAUTHKEY IN VARCHAR2, VAUTHSECRET IN VARCHAR2);

FUNCTION LOGGER ( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLOGGERNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER, VLOGGERLEVEL IN VARCHAR2) RETURN VARCHAR2;

FUNCTION USER(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VUSERLOGIN IN VARCHAR2, VPERSONID IN VARCHAR2, 
	VINVITATIONCODE IN VARCHAR2, VINVITATIONEMAIL IN VARCHAR2, VINVITED IN TIMESTAMP, VINVITATIONEMAILED IN TIMESTAMP, 
	VINITIALIZED IN NUMBER, VPASSWORD IN VARCHAR2, VPASSWORDEXPIRATION IN TIMESTAMP, 
	VFORCEEXPIRATION IN NUMBER, VUSERTYPE IN VARCHAR2, VREGISTRATIONMETHOD IN VARCHAR2, VISACTIVE IN NUMBER, 
	VSECRETKEY IN VARCHAR2,VSALT IN VARCHAR2,VEMAILSCHEDULE IN VARCHAR2, VNOTIFYBYEMAIL IN NUMBER, VVERIFIER IN VARCHAR2) RETURN VARCHAR2;

FUNCTION USERLOGINHISTORY(VID IN VARCHAR2, VUSERID IN VARCHAR2, VLOGGEDIN IN TIMESTAMP, VIPADDRESS IN VARCHAR2) RETURN VARCHAR2;
	
FUNCTION CAMPUSUSER( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VCAMPUSID IN VARCHAR2, VUSERID IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE CAMPUSUSER(VCAMPUS IN VARCHAR2, VUSERLOGIN in VARCHAR2);

PROCEDURE USER(VUSERLOGIN IN VARCHAR2, VINVITATIONCODE IN VARCHAR2, VINVITATIONEMAIL IN VARCHAR2, 
	VINVITED IN TIMESTAMP, VINITIALIZED IN NUMBER, VPASSWORD IN VARCHAR2, VPASSWORDEXPIRATION IN TIMESTAMP, 
	VFORCEEXPIRATION IN NUMBER, VUSERTYPE IN VARCHAR2, VREGISTRATIONMETHOD IN VARCHAR2, VISACTIVE IN NUMBER, 
	VSALT IN VARCHAR2, VEMAILSCHEDULE IN VARCHAR2, VNOTIFYBYEMAIL IN NUMBER, VVERIFIER IN VARCHAR2);

FUNCTION CRONTASK(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VJAVACLASS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VCRONEXPRESSION IN VARCHAR2, VISACTIVE IN NUMBER) RETURN VARCHAR2;
PROCEDURE CRONTASK(VJAVACLASS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, VCRONEXPRESSION IN VARCHAR2, VISACTIVE IN NUMBER);

FUNCTION CRONTASKRUN(VID IN VARCHAR2, VJAVACLASS IN VARCHAR2, VSERVER IN VARCHAR2, VRUNSTART IN TIMESTAMP, VRUNEND IN TIMESTAMP, VSTATUS IN VARCHAR2, VERROR IN VARCHAR2) RETURN VARCHAR2;

FUNCTION BULLETIN ( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLANGUAGE IN VARCHAR2, VPERIODSTART IN TIMESTAMP, 
	VPERIODEND IN TIMESTAMP, VBULLETINTEXT IN VARCHAR2, VCREATED IN TIMESTAMP, VCREATEDBY IN VARCHAR2) RETURN VARCHAR2;

END CORE;
/

show errors
