CREATE OR REPLACE PACKAGE CORE AS

FUNCTION CAMPUS(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VCAMPUS IN VARCHAR2, 
	VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER) RETURN VARCHAR2;

PROCEDURE CAMPUS (VCAMPUS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, 
	VISACTIVE IN NUMBER); 

FUNCTION LIST (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLISTNAME IN VARCHAR2, 
	VDESCRIPTION IN VARCHAR2, VHELPTEXT IN VARCHAR2, VISACTIVE IN NUMBER, 
	VISSYSTEM IN NUMBER) RETURN VARCHAR2;

PROCEDURE LIST (VLISTNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, 
	VHELPTEXT IN VARCHAR2, VISACTIVE IN NUMBER, VISSYSTEM IN NUMBER);

FUNCTION LISTITEM (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VLISTID IN VARCHAR2,
	VISALLCAMPUS IN NUMBER, VCAMPUSID IN VARCHAR2, VDISPLAYORDER IN NUMBER, VSYSTEMVALUE IN VARCHAR2, 
	VVALUE IN VARCHAR2, VISDEFAULT IN NUMBER, VDESCRIPTION IN VARCHAR2) RETURN VARCHAR2;


PROCEDURE LISTITEM (VLISTNAME IN VARCHAR2, VCAMPUS IN VARCHAR2, 
	VISALLCAMPUS IN NUMBER, VDISPLAYORDER IN NUMBER, 
	VSYSTEMVALUE IN VARCHAR2, VVALUE IN VARCHAR2, VISDEFAULT IN NUMBER, 
	VDESCRIPTION IN VARCHAR2); 

FUNCTION USER(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VUSERLOGIN IN VARCHAR2,  
	VFULLNAME IN VARCHAR2, VSORTNAME IN VARCHAR2, VEMPLID IN VARCHAR2,
	VPASSWORD IN VARCHAR2, VISACTIVE IN NUMBER, VSECRETKEY IN VARCHAR2, 
	VCREATED IN DATE, VCREATEDBY IN VARCHAR2) RETURN VARCHAR2;

PROCEDURE USER(VUSERLOGIN IN VARCHAR2,  
	VFULLNAME IN VARCHAR2, VSORTNAME IN VARCHAR2, VEMPLID IN VARCHAR2,
	VPASSWORD IN VARCHAR2, VISACTIVE IN NUMBER, VSECRETKEY IN VARCHAR2);

FUNCTION USERLOGINHISTORY(VID IN VARCHAR2, VUSERID IN VARCHAR2, 
	VLOGGEDIN IN TIMESTAMP, VIPADDRESS IN VARCHAR2) RETURN VARCHAR2;
	
FUNCTION CAMPUSUSER( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, 
	VCAMPUSID IN VARCHAR2, VUSERID IN VARCHAR2) RETURN VARCHAR2;

PROCEDURE CAMPUSUSER(VCAMPUS IN VARCHAR2, VUSERLOGIN in VARCHAR2);

FUNCTION CRONTASK(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VJAVACLASS IN VARCHAR2, 
	VDESCRIPTION IN VARCHAR2, VCRONEXPRESSION IN VARCHAR2, 
	VISACTIVE IN NUMBER) RETURN VARCHAR2;

PROCEDURE CRONTASK(VJAVACLASS IN VARCHAR2, VDESCRIPTION IN VARCHAR2, 
	VCRONEXPRESSION IN VARCHAR2, VISACTIVE IN NUMBER);

FUNCTION CRONTASKRUN(VID IN VARCHAR2, VJAVACLASS IN VARCHAR2, VSERVER IN VARCHAR2, 
	VRUNSTART IN TIMESTAMP, VRUNEND IN TIMESTAMP, VSTATUS IN VARCHAR2, 
	VERROR IN VARCHAR2) RETURN VARCHAR2;

FUNCTION SECURITYGROUP ( VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, 
	VSECURITYGROUPNAME IN VARCHAR2, VDESCRIPTION IN VARCHAR2, 
	VISACTIVE IN NUMBER) RETURN VARCHAR2;

PROCEDURE SECURITYGROUP(VSECURITYGROUPNAME IN VARCHAR2, 
	VDESCRIPTION IN VARCHAR2, VISACTIVE IN NUMBER);

FUNCTION SECURITYGROUPUSER(VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, 
	VSECURITYGROUPID IN VARCHAR2, VUSERID IN VARCHAR2) RETURN VARCHAR2;

PROCEDURE SECURITYGROUPUSER(VSECURITYGROUPNAME IN VARCHAR2, VUSERLOGIN IN VARCHAR2);


FUNCTION PROPERTY (VID IN VARCHAR2, VROWSTAMP IN VARCHAR2, VREFIDTYPE IN VARCHAR2, VREFID in VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2) RETURN VARCHAR2;

PROCEDURE SYSTEMPROPERTY(VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE CAMPUSPROPERTY (VCAMPUS IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE USERPROPERTY (VUSERID IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);
PROCEDURE SECURITYGROUPPROPERTY (VSECURITYGROUPNAME IN VARCHAR2, VPROPERTY IN VARCHAR2, VVALUE IN VARCHAR2);

END CORE;
/

show errors

